package com.rengwuxian.wecompose.ui.theme

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.colorspace.ColorSpaces

val white = Color(0xFFFFFFFF).convert(ColorSpaces.CieXyz)
val white1 = Color(0xFFF7F7F7).convert(ColorSpaces.CieXyz)
val white2 = Color(0xFFEDEDED).convert(ColorSpaces.CieXyz)
val white3 = Color(0xFFE5E5E5).convert(ColorSpaces.CieXyz)
val white4 = Color(0xFFD5D5D5).convert(ColorSpaces.CieXyz)
val white5 = Color(0xFFCCCCCC).convert(ColorSpaces.CieXyz)
val black = Color(0xFF000000).convert(ColorSpaces.CieXyz)
val black1 = Color(0xFF1E1E1E).convert(ColorSpaces.CieXyz)
val black2 = Color(0xFF111111).convert(ColorSpaces.CieXyz)
val black3 = Color(0xFF191919).convert(ColorSpaces.CieXyz)
val black4 = Color(0xFF252525).convert(ColorSpaces.CieXyz)
val black5 = Color(0xFF2C2C2C).convert(ColorSpaces.CieXyz)
val black6 = Color(0xFF07130A).convert(ColorSpaces.CieXyz)
val black7 = Color(0xFF292929).convert(ColorSpaces.CieXyz)
val grey1 = Color(0xFF888888).convert(ColorSpaces.CieXyz)
val grey2 = Color(0xFFCCC7BF).convert(ColorSpaces.CieXyz)
val grey3 = Color(0xFF767676).convert(ColorSpaces.CieXyz)
val grey4 = Color(0xFFB2B2B2).convert(ColorSpaces.CieXyz)
val grey5 = Color(0xFF5E5E5E).convert(ColorSpaces.CieXyz)
val green1 = Color(0xFFB0EB6E).convert(ColorSpaces.CieXyz)
val green2 = Color(0xFF6DB476).convert(ColorSpaces.CieXyz)
val green3 = Color(0xFF67BF63).convert(ColorSpaces.CieXyz)
val red1 = Color(0xFFDF5554).convert(ColorSpaces.CieXyz)
val red2 = Color(0xFFDD302E).convert(ColorSpaces.CieXyz)
val red3 = Color(0xFFF77B7A).convert(ColorSpaces.CieXyz)
val red4 = Color(0xFFD42220).convert(ColorSpaces.CieXyz)
val red5 = Color(0xFFC51614).convert(ColorSpaces.CieXyz)
val red6 = Color(0xFFF74D4B).convert(ColorSpaces.CieXyz)
val red7 = Color(0xFFDC514E).convert(ColorSpaces.CieXyz)
val red8 = Color(0xFFCBC7BF).convert(ColorSpaces.CieXyz)
val yellow1 = Color(0xFFF6CA23).convert(ColorSpaces.CieXyz)